import { Router } from 'express';
import * as c from '../controllers/issues.controller';
import { requireAuth } from '../middleware/auth';
import { upload } from '../middleware/upload';
const r = Router();
r.use(requireAuth);
r.get('/', c.list);
r.get('/my', c.listMine);
r.get('/assigned', c.listAssigned);
r.get('/:id', c.get);
r.post('/', c.create);
r.put('/:id/status', c.setStatus);
r.put('/:id/priority', c.setPriority);
r.put('/:id/assign', c.assign);
r.put('/:id/close', c.close);
r.post('/:id/comments', c.comment);
r.post('/:id/photo', upload.single('photo'), c.uploadPhoto);
r.delete('/:id', c.remove);
export default r;
